name: crime_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - contextily
  - folium
  - pysal